AREAS = [
{
 "slug": "oak-hills", "name": "Oak Hills", "short": "Oak Hills", "group": "around", "kind": "county",
 "lat": 45.5395, "lng": -122.8330, "gq": "Oak Hills, OR", "zoom": 15,
 "title": "Tree Service Oak Hills, OR | Removal, Trimming & Stumps",
 "description": "Tree service in Oak Hills, OR: mature oaks and firs in a 1960s planned community, with HOA commons and historic district covenants. (503) 386-0199.",
 "og": "A mid-century planned community built around its trees, where the homeowners association has the first say.",
 "h1": "Tree service in Oak Hills, Oregon",
 "card": "A 1960s planned community north of the Sunset Highway, listed on the National Register of Historic Places. Greenways, shared commons and sixty-year-old trees, managed under one of the most active homeowners associations in the county.",
 "facts": "ZIP 97006. Unincorporated Washington County, with a Beaverton mailing address.",
 "intro": ["Oak Hills was laid out in the mid-1960s as a complete community, with houses and townhomes arranged around shared greenways, a recreation center and a school. In 2013 it was listed on the National Register of Historic Places as a mid-century planned community, the first of its kind in Oregon to be recognized that way.",
           "The design put trees at the center. Native oaks and firs were kept where they stood, the commons were planted generously, and sixty years later the canopy is the neighborhood's most valuable feature and its biggest maintenance item."],
 "trees": ["The trees are all about the same age, which means they are all reaching the same stage together. The planted maples, sweetgums, birches and pines are mature to over-mature. Birches are dying of bronze birch borer, sweetgums break in ice, and pines planted close to houses have outgrown their spots.",
           "The native trees are older still. The Oregon white oaks that gave the community its name and the Douglas-firs kept from the original woodland are the ones most worth careful work. Oaks in particular dislike summer irrigation and soil disturbance under their canopy, both of which are hard to avoid in a landscaped yard.",
           "Because the greenways run behind most lots, a large share of the trees that shade Oak Hills homes stand on association land. That decides who pays attention to them, who approves work on them, and who is responsible if one fails."],
 "jobs": [["Pruning mature yard trees to the association's standards", "Deadwood, clearance and reduction on sixty-year-old trees, done so the result fits the neighborhood's character. No topping and no lion-tailing.", "/tree-trimming/", "Tree trimming and maintenance"],
          ["Removing over-mature pines and birches", "Dead and failing trees taken down in sections in small yards and courtyards, once the association has signed off.", "/tree-removal/", "Tree removal"],
          ["Careful work on native oaks", "Conservative deadwood removal and clearance on Oregon white oaks, and advice on what to change on the ground around them.", "/tree-trimming/", "Tree trimming and maintenance"],
          ["Stumps in townhome courtyards", "Grinding where the only access is a gate or a path, using a compact machine, with utilities located first.", "/stump-grinding/", "Stump grinding"]],
 "places": [["The commons and greenways", "The shared open space behind the houses is the association's property, and so are its trees. If one overhangs your lot or looks unsafe, report it to the association in writing. You may not prune or remove it yourself."],
            ["Around Oak Hills Elementary", "The school sits in the middle of the community beside the recreation center, surrounded by some of the original oaks and firs. It is the easiest place to see how large the neighborhood's native trees have become."],
            ["The townhome clusters", "Attached homes share walls, courtyards and landscape strips. A tree in a courtyard can belong to one owner, to several, or to the townhome association, and it is worth finding out which before requesting an estimate."],
            ["The Sunset Highway edge", "Homes along the south side back onto the highway corridor and its sound walls. Trees there screen noise and take the east wind that funnels along the highway in winter."]],
 "rules": ["county"],
 "rules_intro": "Oak Hills is unincorporated, so no city tree code applies. In practice the homeowners association is the rule-maker here.",
 "rules_note": "The National Register listing recognizes the community's design and does not by itself regulate what you do with a tree in your yard. The association's covenants and design guidelines do. They cover common-area trees entirely and can cover visible changes to private lots. Ask the association before removing a significant tree, and get the answer in writing. We can supply the written assessment that boards usually want.",
 "faq": [["Do I need approval to remove a tree in Oak Hills?", "From the county, usually not, because Oak Hills is unincorporated. From the homeowners association, quite possibly. Common-area trees are entirely theirs, and the covenants can apply to trees on private lots. Ask before you book the work."],
         ["Does the historic district listing protect my trees?", "Not directly. National Register listing is an honor and brings no tree permit with it. The rules that matter come from the association's covenants and design guidelines, which were written to protect the character that earned the listing."],
         ["A tree in the greenway hangs over my roof. Who prunes it?", "The association, because it is their tree. Report it in writing with photos. They can hire the work or give you permission to have it done. Without that permission, leave it alone."],
         ["How should I care for a native oak in my yard?", "Mostly by leaving the ground under it alone. Keep irrigation, new soil, paving and trenching away from the root zone, and limit pruning to dead and hazardous limbs. Oregon white oaks decline from kindness more often than from neglect."]],
},
{
 "slug": "cedar-hills", "name": "Cedar Hills", "short": "Cedar Hills", "group": "around", "kind": "county",
 "lat": 45.5048, "lng": -122.7984, "gq": "Cedar Hills, OR", "zoom": 14,
 "title": "Tree Service Cedar Hills, OR | Removal, Trimming & Stumps",
 "description": "Tree service in Cedar Hills, OR: seventy-year-old street and yard trees on small postwar lots, overhead wires and homes association rules. (503) 386-0199.",
 "og": "Postwar lots, seventy-year-old trees, overhead wires and a homes association with covenants of its own.",
 "h1": "Tree service in Cedar Hills, Oregon",
 "card": "One of Oregon's largest postwar planned neighborhoods, just north of Beaverton. Small lots, seventy-year-old trees, overhead utility lines and a homes association with covenants.",
 "facts": "ZIPs 97005 and 97225. Unincorporated Washington County, between the Sunset Highway and Walker Road.",
 "intro": ["Cedar Hills was built between 1946 and the early 1960s as a single planned development of more than two thousand homes, which made it one of the largest of its kind in Oregon. It sits just north of Beaverton, tucked against the Sunset Highway and Highway 217.",
           "The houses are modest and the lots are small, but the trees have had seventy years to grow. That mismatch, big trees on small lots under overhead wires, describes nearly every job we do here."],
 "trees": ["The original plantings are now very large. Street-side maples, sweetgums and flowering cherries from the 1950s have reached the end of what a narrow strip can support, and the backyards hold Douglas-firs and cedars that started as seedlings when the first owners moved in. Deadwood, decay at old pruning wounds and lifted sidewalks are everywhere.",
           "Power and phone lines run on poles along most streets, often through the crowns of the street trees. Decades of utility clearance pruning have left many of those trees lopsided, with heavy growth leaning over the houses. Correcting that balance is slow, careful work over several years.",
           "Small lots mean little room. A backyard fir is usually within reach of three or four roofs, and the only way in is a side gate. Nearly everything is climbed, rigged and carried out by hand."],
 "jobs": [["Rebalancing trees pruned for the wires", "Reduction of the heavy side that has grown over the house, so the tree carries its weight more evenly. PGE handles the side facing the high-voltage lines.", "/tree-trimming/", "Tree trimming and maintenance"],
          ["Removing seventy-year-old street trees", "Maples and sweetgums with serious decay or with roots that have broken the sidewalk. The stump usually comes out too, so a smaller tree can be planted in its place.", "/tree-removal/", "Tree removal"],
          ["Backyard firs among close neighbors", "Sectional removal with everything lowered on ropes, and conversations with the neighbors on each side before the day.", "/tree-removal/", "Tree removal"],
          ["Limbs on roofs and service lines", "Old cherries and maples shed large limbs in ice and wet snow. Call PGE first if a line is involved, then us.", "/emergency-tree-service/", "Emergency tree service"]],
 "places": [["Commonwealth Lake Park", "The pond and its loop path are lined with willows, cottonwoods and planted conifers. Homes around the lake sit on wetter ground than the rest of Cedar Hills, where trees root shallowly and grow fast."],
            ["Cedar Hills Park and the recreation center", "The park's large firs and maples are the same age as the neighborhood's, and they are pruned on a schedule. They are a fair guide to what a well-kept seventy-year-old tree should look like."],
            ["Cedar Hills Boulevard", "The main street carries steady traffic, so tree work beside it needs traffic control and, when a lane is affected, a county right-of-way permit."],
            ["The Sunset Highway and Highway 217 edges", "Streets along the north and east edges back onto highway sound walls. Trees there were planted as screens, and they take the east wind that follows the Sunset Highway corridor in winter."]],
 "rules": ["county"],
 "rules_intro": "Cedar Hills is unincorporated. The shopping center to the south that shares its name is inside Beaverton, but the neighborhood is not.",
 "rules_note": "Nearly every home belongs to the Homes Association of Cedar Hills, whose covenants date from the original development and include review of changes to a property. Check them before removing a large front-yard tree. The county's own rules come into play along the creeks and wherever work affects a county road.",
 "faq": [["Do Beaverton's tree rules apply in Cedar Hills?", "No. Cedar Hills is unincorporated Washington County, even though Beaverton surrounds much of it. There is no city street tree permit here. The homes association's covenants and the county's rules for creek corridors and road work are what apply."],
         ["The power company pruned my tree into a lopsided shape. Can it be fixed?", "It can be improved. Over two or three prunings we reduce the heavy side over the house and encourage growth where the tree needs it. The side facing the high-voltage lines stays with PGE's crews."],
         ["Can a large tree be removed from a small Cedar Hills backyard?", "Yes. It comes down in sections on ropes, and the wood goes out through the side gate by hand or on a narrow loader. We talk to the neighbors whose yards are underneath before the day of the work."],
         ["What should I plant after removing an old street tree?", "Something that fits the space. Under wires and in narrow strips that means a small-maturing tree. Take the old stump out first, so the new tree is not planted into rotting wood."]],
},
{
 "slug": "raleigh-hills", "name": "Raleigh Hills", "short": "Raleigh Hills", "group": "around", "kind": "county",
 "lat": 45.4807, "lng": -122.7620, "gq": "Raleigh Hills, OR", "zoom": 14,
 "title": "Tree Service Raleigh Hills, OR | Removal, Trimming & Stumps",
 "description": "Tree service in Raleigh Hills, OR: large old firs on generous lots, Fanno Creek headwaters and a Portland boundary worth checking. (503) 386-0199.",
 "og": "Big lots, big firs, the upper reaches of Fanno Creek and three jurisdictions within a few blocks.",
 "h1": "Tree service in Raleigh Hills, Oregon",
 "card": "Unincorporated community east of Beaverton where Beaverton-Hillsdale Highway, Scholls Ferry Road and Oleson Road meet. Generous lots, very large firs, and the Portland city line a few blocks away.",
 "facts": "ZIPs 97225 and 97221. Unincorporated Washington County, with Portland mailing addresses.",
 "intro": ["Raleigh Hills grew up around the junction of Beaverton-Hillsdale Highway, Scholls Ferry Road and Oleson Road. Homes date from the 1940s through the 1960s, the lots are larger than almost anywhere else nearby, and many streets have no sidewalks and a rural feel that the trees have a lot to do with.",
           "It is also a border community. Beaverton is a few blocks to the west and the Portland city line, which is also the county line, is a few blocks to the east. Three sets of tree rules operate within a short walk of each other."],
 "trees": ["Large lots grow large trees. Douglas-firs over a hundred and twenty feet are common, along with big western redcedars, bigleaf maples and a good number of mature ornamental trees planted by the first owners: copper beech, dogwood, Japanese maple and the occasional giant sequoia.",
           "With room around them, many of these trees have full crowns down to the ground and long lower limbs, which is handsome and heavy. Long limbs over driveways and roofs are the usual concern, and end-weight reduction is usually the answer.",
           "Fanno Creek begins in the hills just east of here and gathers several small tributaries through Raleigh Hills. Yards along those channels hold alder, ash and cottonwood on wet ground, inside corridors that are regulated."],
 "jobs": [["Large-tree pruning", "Deadwood, hangers and reduction of long limbs on firs, cedars and maples, along with proper care for the ornamental trees that give these gardens their character.", "/tree-trimming/", "Tree trimming and maintenance"],
          ["Removing very large firs", "Trees over a hundred feet taken down in sections. Larger lots sometimes allow bigger pieces and a faster job, and we say which applies after seeing the site.", "/tree-removal/", "Tree removal"],
          ["Long driveways blocked by fallen trees", "Deep lots and private lanes mean one fallen tree can shut several households in. We open the lane first.", "/emergency-tree-service/", "Emergency tree service"],
          ["Stumps in established gardens", "Grinding among mature plantings, with plywood to protect beds and paths, or full removal where a wall or a terrace is planned.", "/stump-removal/", "Stump removal"]],
 "places": [["The Raleigh Hills crossroads", "The junction of three highways is commercial and busy. Two of those roads are state highways, so trees beside them fall under the state's rules, not the county's."],
            ["Raleigh Park", "The neighborhood park and swim center sit among large native firs and cedars. They are a good measure of how big the area's trees get when they are given room and left untopped."],
            ["The streets around Portland Golf Club", "The course has some of the oldest planted trees in the area, and the streets beside it have the large lots and mature gardens Raleigh Hills is known for. Trees along the fairway edges take more wind than those inside the blocks."],
            ["Fanno Creek's upper channels", "Small creeks cross back yards on their way to Fanno Creek. Even a channel you can step across usually has a regulated vegetated corridor on both banks."]],
 "rules": ["county"],
 "rules_intro": "Raleigh Hills is unincorporated Washington County. The Portland mailing address does not bring Portland's tree code with it, but the real city line is close.",
 "rules_note": "If your street is near the county line, confirm which side you are on. Inside Portland, removing a private tree a foot or more across generally needs a city permit, which is far stricter than anything on the Washington County side. On the county side the tests are creek corridors, mapped natural resource areas and right-of-way work. State highways have their own permits.",
 "faq": [["Do I need a permit to remove a tree in Raleigh Hills?", "Usually not for an ordinary yard tree, because Raleigh Hills is unincorporated Washington County. Trees along Fanno Creek's channels or in a mapped natural resource area are the exception. If you are near the Portland line, confirm which side you are on."],
         ["My address says Portland. Does Portland's tree code apply?", "Only if you are inside the city limits, and most of Raleigh Hills is not. The mailing address comes from the post office. Your property tax statement shows whether the City of Portland is one of your taxing districts."],
         ["Should I thin the lower limbs of my big fir?", "Only for a reason, such as clearance over a roof or a driveway. Low limbs help stabilize the trunk and feed the tree. Removing many of them at once, called over-raising, makes a tree top-heavy and more likely to snap."],
         ["Can you protect my garden while removing a tree?", "Yes. Plywood and mats go over beds and paths, pieces are lowered on ropes instead of dropped, and we plan the route for the wood with you beforehand. It is slower than working in an open yard, and the estimate reflects the time involved."]],
},
{
 "slug": "garden-home-whitford", "name": "Garden Home and Whitford", "short": "Garden Home", "group": "around", "kind": "county",
 "lat": 45.4640, "lng": -122.7590, "gq": "Garden Home Recreation Center, Portland, OR", "zoom": 14,
 "title": "Tree Service Garden Home, OR | Removal, Trimming & Stumps",
 "description": "Tree service in Garden Home and Whitford, OR: tall firs over older homes, Ash Creek and Fanno Creek corridors, and county rules. (503) 386-0199.",
 "og": "Older homes under tall firs, two creek corridors, and the Portland and Tigard lines close by.",
 "h1": "Tree service in Garden Home and Whitford, Oregon",
 "card": "Unincorporated community southeast of Beaverton around Oleson Road and Garden Home Road. Older homes under tall firs, two creek corridors and the Portland and Tigard city lines nearby.",
 "facts": "ZIP 97223. Unincorporated Washington County, with Portland mailing addresses.",
 "intro": ["Garden Home began as a stop on the Oregon Electric Railway in the early 1900s, and the old rail grade is now the start of the Fanno Creek Trail at the Garden Home Recreation Center. The community spreads out from Oleson Road and Garden Home Road, with Whitford on its west side toward Highway 217.",
           "Homes range from prewar cottages to 1970s ranches, with new infill on divided lots. Almost all of it sits under tall second-growth Douglas-fir, and the two creeks that cross the area add a band of wet-ground trees."],
 "trees": ["The firs here came up after the area was logged more than a century ago, and they now stand well over a hundred feet above one-story houses. They were never thinned, so many grew as close groups with narrow crowns. Groups like that are stable together and much less so when one or two are removed from the middle.",
           "Infill building is the newest pressure. When a deep lot is divided, the new foundation, driveway and utility trenches cut through the roots of trees on both the new lot and the neighbors'. The damage doesn't show for a few years, then appears as a thinning top or a tree down in a storm.",
           "Along Ash Creek and Fanno Creek the trees are alder, cottonwood, willow and Oregon ash. They grow fast, fail young, and stand inside regulated corridors. With emerald ash borer now in Washington County, the ash are on borrowed time unless they are treated."],
 "jobs": [["Firs next to new construction", "Assessing and pruning trees whose roots were cut by a neighboring build, and removing the ones that have lost too much to stand safely.", "/tree-removal/", "Tree removal"],
          ["Deadwood and roof clearance", "Routine care for tall firs over older roofs: dead limbs out, low limbs off the shingles, a look at the top and the base.", "/tree-trimming/", "Tree trimming and maintenance"],
          ["Creek-side trees down in winter", "Alders and cottonwoods that tip over on saturated ground along the creeks. We clear your side and explain what may have to stay in the corridor.", "/emergency-tree-service/", "Emergency tree service"],
          ["Stumps on lots being divided or built on", "Anything under a future driveway or foundation is dug out and the hole compacted, not ground.", "/stump-removal/", "Stump removal"]],
 "places": [["Garden Home Recreation Center and the Fanno Creek Trail", "The trail starts here on the old rail grade. It is lined with the area's typical trees, and the wet stretches show how alder and ash behave as they age: dead tops, leaning trunks and fallen limbs."],
            ["Oleson Road", "The main north to south road is a county road with heavy traffic. Tree work beside it needs traffic control and a right-of-way permit when a lane is affected."],
            ["Ash Creek", "The creek runs through the south side of Garden Home toward Tigard. Its banks carry a regulated vegetated corridor, and many back yards end inside it."],
            ["Whitford and the Highway 217 side", "West toward the highway the streets are a little newer and the lots more regular. The boundary with Beaverton runs through this area, so neighbors a block apart can have different street tree rules."]],
 "rules": ["county"],
 "rules_intro": "Garden Home and Whitford are unincorporated Washington County. Portland lies to the east, Tigard to the south and Beaverton to the west, each with a tree code of its own.",
 "rules_note": "Check which jurisdiction you are in if your street is near an edge. On the county side, ordinary yard trees are generally the owner's to manage. The exceptions are the Ash Creek and Fanno Creek corridors, which Clean Water Services regulates, and any tree a land division was required to protect. Lots being divided often come with tree protection conditions, so ask before clearing for a build.",
 "faq": [["Do I need a permit to remove a tree in Garden Home?", "For an ordinary yard tree, usually not, since Garden Home is unincorporated county. Trees in the Ash Creek or Fanno Creek corridors are regulated, and a lot being divided may carry tree protection conditions. Check those two things first."],
         ["A new house is going in next door. Will it hurt my trees?", "It can. Foundations, driveways and utility trenches inside the spread of your tree's branches cut its roots. Ask the builder where trenches will run, photograph your trees now, and have them looked at before and after the work."],
         ["My firs grow in a tight group. Can I remove just one?", "Sometimes, but think about the rest. Firs that grew together shelter one another, and taking one from the middle or the windward side exposes the others. We look at the whole group before recommending which trees can go."],
         ["Is Garden Home part of Portland or Beaverton?", "Neither. It is unincorporated Washington County with a Portland mailing address. Portland's city line runs along its east side, Beaverton's along the west and Tigard's to the south, so it is worth confirming near the edges."]],
},
{
 "slug": "hillsboro", "name": "Hillsboro", "short": "Hillsboro", "group": "around", "kind": "hillsboro",
 "lat": 45.5229, "lng": -122.9898, "gq": "Hillsboro, OR", "zoom": 12,
 "title": "Tree Service Hillsboro, OR | Removal, Trimming & Stumps",
 "description": "Tree service in Hillsboro, OR: street tree permits handled, heritage oaks, storm cleanup and stump work from Orenco to downtown. (503) 386-0199.",
 "og": "Hillsboro's free street tree permit, its oak savanna remnants, and tree work from Tanasbourne and Orenco to downtown.",
 "h1": "Tree service in Hillsboro, Oregon",
 "card": "The county seat, west of our office. Old street trees downtown, oak remnants around Orenco, newer subdivisions everywhere else, and a city code that requires a free permit for street tree work.",
 "facts": "ZIPs 97123, 97124 and 97006. City of Hillsboro, a Tree City USA community since 2018.",
 "intro": ["Hillsboro starts a few blocks west of our office and runs to the far side of the county seat's old downtown. It covers a lot of ground and a lot of tree types: century-old street trees in the downtown neighborhoods, Oregon white oaks around Orenco, and twenty years of new subdivisions with young trees planted close together.",
           "It is its own city with its own tree code, which centers on the public right-of-way. If the tree is a street tree, Hillsboro wants a permit first. The permit is free, and it is required for removal, replacement and major pruning."],
 "trees": ["Downtown and the older neighborhoods east of it have the big trees: bigleaf maples, elms, walnuts and Douglas-firs from the early 1900s, many in planting strips that were generous once and are tight now. Their size is an asset, and their deadwood over streets and sidewalks is the owner's responsibility.",
           "The Tualatin Valley floor was oak savanna before it was farmed, and Hillsboro still has remnants, most visibly at Orenco Woods and along Rock Creek. A mature Oregon white oak on a home lot is worth careful treatment: little pruning, no summer irrigation under the canopy, and no digging in the root zone.",
           "In the newer subdivisions the trees are young and were planted for quick effect: red maples, pears, zelkovas and ash in narrow strips. Pears and ash are the ones to watch. Pears split in ice, and emerald ash borer was first found in Oregon in 2022 in Forest Grove, just west of Hillsboro."],
 "jobs": [["Street tree pruning to city standards", "Clearance of 8 feet over sidewalks and 15 feet over streets, done to ANSI A300 standards, with the Tree Care Permit in hand when the pruning is heavy enough to need one.", "/tree-trimming/", "Tree trimming and maintenance"],
          ["Permitted street tree removal and replacement", "Removal under the city's permit, the stump taken out, and the strip left ready for the required replacement tree.", "/tree-removal/", "Tree removal"],
          ["Ice and wind damage", "Split pears, broken maple limbs and trees across driveways after winter storms.", "/emergency-tree-service/", "Emergency tree service"],
          ["Stump grinding in new subdivisions", "Small yards with utilities and irrigation close to the surface, so the 811 locate and a walk-through come first.", "/stump-grinding/", "Stump grinding"]],
 "places": [["Downtown and Shute Park", "The city's oldest park and the streets around the courthouse have Hillsboro's largest planted trees. Big old street trees here are the adjoining owners' to maintain, and removing one takes a permit and a replacement."],
            ["Orenco and Orenco Woods", "Orenco began as a nursery company town, and the nature park beside it keeps oak woodland along Rock Creek. The neighborhoods around it mix preserved oaks with dense new street tree plantings."],
            ["Jackson Bottom Wetlands", "The preserve on the Tualatin River floodplain south of downtown is ash, willow and cottonwood country. Properties near the floodplain share those species and the regulations that come with wet ground."],
            ["Tanasbourne and AmberGlen", "The east end of the city, around our office, is apartments, shops and offices with required landscape trees. We cover it on its own page, together with Rock Creek."]],
 "rules": ["hillsboro"],
 "rules_intro": "Hillsboro has its own tree code, separate from Beaverton's and from the county's. It is built around trees in the public right-of-way.",
 "rules_note": "Contractors working for a property owner also need the Tree Care Permit before touching a street tree, so we obtain it as part of the job. Pockets around Hillsboro, including much of Reedville, are still unincorporated, and there the county's rules apply instead. Trees in mapped natural resource areas along Rock Creek, McKay Creek and the Tualatin River are regulated whoever owns them.",
 "faq": [["Do I need a permit to remove a street tree in Hillsboro?", "Yes. Hillsboro requires its free Tree Care Permit before a street tree is planted, removed or replaced, and the removed tree has to be replaced. Contractors need the permit too, so we obtain it as part of the job."],
         ["Do I need a permit to prune my street tree in Hillsboro?", "For light pruning, no. Major pruning needs the free permit: removing branches or roots 2 inches across or larger, or more than 20 percent of the crown. So does any pruning that blocks a sidewalk or a traffic lane while it is done."],
         ["How high must branches clear the street in Hillsboro?", "Eight feet over sidewalks and 15 feet over streets and alleys. The 15-foot figure took effect in 2020 to protect garbage trucks, buses and city vehicles. The owner next to the tree is responsible for keeping that clearance."],
         ["Do I need a permit to remove a tree in my Hillsboro backyard?", "Generally not. Hillsboro's code focuses on right-of-way trees. The exceptions are trees in mapped natural resource areas and trees a development approval required. If your lot backs onto a creek or a greenway, check first."]],
},
{
 "slug": "tigard", "name": "Tigard", "short": "Tigard", "group": "around", "kind": "tigard",
 "lat": 45.4312, "lng": -122.7715, "gq": "Tigard, OR", "zoom": 13,
 "title": "Tree Service Tigard, OR | Tree Removal, Trimming & Stumps",
 "description": "Tree service in Tigard, OR: six kinds of protected tree, Fanno Creek and Bull Mountain lots, storm cleanup and stump work. (503) 386-0199.",
 "og": "Tigard's six categories of permit-required trees, sensitive lands along Fanno Creek, and the wind on Bull Mountain.",
 "h1": "Tree service in Tigard, Oregon",
 "card": "The city south of Beaverton, from Fanno Creek and downtown to the slopes of Bull Mountain. Tigard's urban forestry code names six kinds of tree that need a removal permit, and most home lots have at least one to think about.",
 "facts": "ZIPs 97223 and 97224. City of Tigard, with unincorporated pockets on Bull Mountain and in Metzger.",
 "intro": ["Tigard lies directly south of Beaverton across Scholls Ferry Road. Fanno Creek runs through the middle of it, the Tualatin River forms its southern edge, and Bull Mountain rises on the west side. Each of those has its own kind of tree and its own kind of tree problem.",
           "Tigard also has one of the more detailed tree codes in the county. It doesn't regulate every backyard tree, but it names six categories that need a removal permit, and it is worth knowing them before you plan any work."],
 "trees": ["Along Fanno Creek and its tributaries the trees are Oregon ash, alder, cottonwood and willow on wet ground. Much of that land counts as sensitive lands under the city's code, which protects native trees there. It is also prime ground for emerald ash borer, now confirmed just to the north in Beaverton.",
           "Bull Mountain is the opposite: dry, exposed and steep, with Douglas-fir and some Oregon white oak left among subdivisions built from the 1990s on. Wind is the main force on the upper slopes, and steep slopes are another of the city's sensitive land categories.",
           "In between are forty- and fifty-year-old neighborhoods with mature street trees, and newer ones where the trees were required by the development's approval. Those development-required trees stay protected long after the builder has gone."],
 "jobs": [["Permitted street tree work", "Pruning to the city's clearances, and removal and replacement under a Tigard permit when a street tree has failed or outgrown its strip.", "/tree-trimming/", "Tree trimming and maintenance"],
          ["Hazard trees on sensitive lands", "Dead and failing trees near creeks and on steep slopes, handled through the city's permit process with a written assessment, often leaving a wildlife snag or the stump in place.", "/tree-removal/", "Tree removal"],
          ["Wind damage on Bull Mountain", "Snapped tops, uprooted firs and limbs on roofs after winter storms from the south and east.", "/emergency-tree-service/", "Emergency tree service"],
          ["Stumps for replacement planting", "Most permitted street tree removals in Tigard come with a replacement requirement, so the old stump is taken out to make room.", "/stump-removal/", "Stump removal"]],
 "places": [["Fanno Creek and downtown", "The creek and its trail pass right behind Main Street. The floodplain and stream corridor are sensitive lands, where native trees need a permit to remove even on private property."],
            ["Cook Park and the Tualatin River", "The city's largest park sits on the river floodplain among big cottonwoods, ash and oaks. Neighborhoods nearby share the high water table, and their trees root shallowly because of it."],
            ["Bull Mountain", "Views, slopes and wind. Parts of the mountain are still unincorporated, so neighbors on the same street can fall under different rules. View pruning here should never mean topping."],
            ["Summerlake and the Scholls Ferry side", "The north side of Tigard, next to Beaverton, is 1980s and 1990s subdivisions around Summer Lake and its creek. Street trees here are mature, and many lots touch the creek corridor."]],
 "rules": ["tigard"],
 "rules_intro": "Tigard has its own urban forestry code, and it differs from Beaverton's in an important way: it lists exactly which trees need a permit.",
 "rules_note": "Simple cases, such as a dead street tree, are decided by city staff. More complex ones go to a board. The city can also require a replacement tree or a contribution to its tree fund. Bull Mountain and Metzger include unincorporated pockets where the county's rules apply instead. Tigard also designates heritage trees, which need a permit wherever they stand.",
 "faq": [["Do I need a permit to remove a tree in Tigard?", "Only if it is one of six kinds: a street tree, a median tree, a heritage tree, a tree planted with the Urban Forestry Fund, a tree required by a development approval, or a native tree on sensitive lands. Other trees on a single-family lot need none."],
         ["What counts as sensitive lands in Tigard?", "Steep slopes, the 100-year floodplain, stream corridors, wetlands and significant habitat areas. Native trees standing on any of those need a removal permit, even in a private back yard. Lots along Fanno Creek and on Bull Mountain are the usual cases."],
         ["Can I remove the street tree in front of my Tigard house?", "With the city's approval. Street tree removals go through either a staff decision or a board decision, depending on how simple the case is, and in most cases a replacement tree is required."],
         ["Is Bull Mountain inside Tigard?", "Partly. Much of it has been annexed, but some areas are still unincorporated Washington County, where Tigard's permit categories don't apply. Your property tax statement shows whether the City of Tigard is one of your taxing districts."]],
},
]
