from guide_kit import tabs, chooser, hotspots, figure, halos

def P(*paras): return '<div class="prose">' + "".join(paras) + '</div>'

# ---------------------------------------------------------------- 1. permit guide
PERMIT_SVG = ('<svg class="viz" viewBox="0 0 640 470" role="img" aria-labelledby="pg-t pg-d"><title id="pg-t">Plan of a Beaverton lot showing five kinds of tree and who regulates each</title>'
 '<desc id="pg-d">A street tree in the planting strip, an ordinary front yard tree, a preserved grove in the back yard, trees inside a creek buffer, and landscape trees on a neighboring commercial lot.</desc>'
 '<rect width="640" height="470" fill="#E6EDE3"/><path d="M0 34Q160 10 320 36T640 30" fill="none" stroke="#8DB6D6" stroke-width="16"/><rect x="0" y="50" width="640" height="52" fill="#9CCB86" fill-opacity=".35"/><path d="M0 102H640" stroke="#2F6B4F" stroke-width="2" stroke-dasharray="9 6"/>'
 '<rect x="40" y="60" width="400" height="300" fill="#DCE9D6" stroke="#6D7F75" stroke-width="1.6" stroke-dasharray="10 5 2 5"/><rect x="460" y="60" width="160" height="300" fill="#D6DBD5" stroke="#6D7F75" stroke-width="1.6"/>'
 '<path d="M480 120H600M480 200H600M480 280H600" stroke="#fff" stroke-width="3" stroke-dasharray="14 10"/><g fill="#7FAE92" stroke="#2F6B4F" stroke-width="1.6"><circle cx="500" cy="160" r="15"/><circle cx="580" cy="160" r="15"/><circle cx="500" cy="240" r="15"/><circle cx="580" cy="240" r="15"/></g>'
 '<rect x="160" y="180" width="180" height="110" fill="#fff" stroke="#12382C" stroke-width="2.5"/><path d="M160 180 205 235 160 290M340 180 295 235 340 290M205 235H295" fill="none" stroke="#A9B8AE" stroke-width="1.4"/>'
 '<path d="M74 84a70 52 0 1 0 110 40a60 46 0 0 0-110-40Z" fill="none" stroke="#12382C" stroke-width="1.8" stroke-dasharray="7 5"/><g fill="#2F6B4F" fill-opacity=".6" stroke="#12382C" stroke-width="1.6"><circle cx="106" cy="112" r="22"/><circle cx="150" cy="96" r="20"/><circle cx="136" cy="146" r="23"/></g>'
 '<circle cx="390" cy="318" r="28" fill="#7FAE92" fill-opacity=".6" stroke="#2F6B4F" stroke-width="1.8"/><circle cx="390" cy="318" r="3" fill="#12382C"/>'
 '<rect x="0" y="360" width="640" height="25" fill="#ECEFE9"/><rect x="0" y="385" width="640" height="25" fill="#D5E4D8"/><rect x="0" y="410" width="640" height="60" fill="#C9D0CA"/><path d="M0 410H640" stroke="#7E8F86" stroke-width="2.5"/><path d="M0 442H640" stroke="#FAFCF8" stroke-width="3" stroke-dasharray="26 22"/>'
 '<circle cx="240" cy="397" r="24" fill="#7FAE92" fill-opacity=".65" stroke="#2F6B4F" stroke-width="1.8"/><circle cx="240" cy="397" r="3" fill="#12382C"/>'
 '<text x="250" y="240" text-anchor="middle">house</text><text x="540" y="340" text-anchor="middle">apartments next door</text><text x="20" y="92">creek buffer</text>'
 + halos([(1, 240, 397, 36), (2, 390, 318, 40), (3, 130, 118, 62), (4, 320, 70, 44), (5, 540, 200, 70)]) + '</svg>')

PERMIT = {
 "slug": "beaverton-tree-removal-permit", "short": "Tree removal permits in Beaverton", "form": "Tree removal",
 "title": "Beaverton Tree Removal Permit Guide | Who Needs One (2026)",
 "description": "Do you need a permit to remove a tree in Beaverton, OR? Street trees, protected backyard trees, county lots, Hillsboro and Tigard, in plain language.",
 "og": "Street trees always need one. Most backyard trees don't. Here is how to tell which kind you have.",
 "h1": "Do you need a permit to remove a tree in Beaverton?",
 "card": "Street trees always need one, most backyard trees don't, and the exceptions are where people get caught. Includes a tagged lot plan and a rule summary for the county, Hillsboro and Tigard.",
 "lede": "The honest answer is: it depends on where the tree stands and whose rules cover that spot. Other tree companies' pages contradict each other on this, so this guide sticks to what the city code and the development code say, and tells you who makes the final call.",
 "tldr": ["A tree between the sidewalk and the street is a <strong>street tree</strong>. Removing it always needs a city permit, and usually a replacement.",
          "An ordinary backyard tree usually needs <strong>no permit</strong>.",
          "Backyard trees that are <strong>protected</strong> do: those in preserved groves, natural resource areas, approved landscape plans, and designated significant or historic trees.",
          "A Beaverton mailing address is not proof you are in Beaverton. Much of Aloha, Cedar Mill and Bethany is <strong>unincorporated</strong>, and the city rules don't apply there.",
          "The Planning Division, 503-526-2420, decides. We check before we book any removal."],
 "sections": [
  {"h2": "Start with two questions", "small": "Pick a tag on the plan to see how each kind of tree is treated.",
   "html": P("<p>Every permit question comes down to two things. First, <strong>where does the tree stand</strong>: in the public right-of-way, in your yard, or in a protected part of your yard? Second, <strong>whose rules apply</strong>: the City of Beaverton's, Washington County's, or another city's? The drawing shows the five situations we run into most often on a single Beaverton block.</p>")
   + hotspots(PERMIT_SVG,
      [(1, 42, 78, "Street tree in the planting strip"), (2, 65.5, 62, "Ordinary front yard tree"), (3, 29, 16, "Preserved grove in the back yard"), (4, 56, 9, "Trees inside the creek buffer"), (5, 90, 36, "Landscape trees on the apartment site")],
      [(1, "The street tree", "<p>It stands in the public right-of-way. The adjoining owner maintains it, but nobody may remove it without a city permit, and a permitted removal normally comes with a replacement from the city's approved list. Cutting 20 percent or more of its crown, trunk or roots counts as removal too.</p>"),
       (2, "The ordinary yard tree", "<p>A tree you or a previous owner planted, outside any protected area, is generally yours to manage. Removing one needs no permit in most cases. The development code does track healthy trees 10 inches across and larger as community trees, so removing several in one year can bring a review.</p>"),
       (3, "The preserved grove", "<p>When a subdivision was approved, the builder was often required to keep a stand of native trees. Those trees are protected as a significant grove or as a condition of approval, even though they now stand in private back yards. Removing one goes through the city, and sometimes the homeowners association as well.</p>"),
       (4, "Trees in the creek buffer", "<p>Creeks and wetlands have regulated buffers. Inside the city they are significant natural resource areas, and across urban Washington County Clean Water Services regulates vegetated corridors. Trees inside the buffer are protected on private land too, and that usually includes dead ones.</p>"),
       (5, "Landscape trees on a commercial or apartment site", "<p>Trees planted under an approved landscape plan are protected landscape trees. That covers nearly every tree at an apartment complex, a shopping center or an office park, and most HOA common-area trees. A manager's or a board's approval doesn't replace the city's.</p>")])},
  {"h2": "Street trees: always a permit",
   "html": P("<p>Beaverton's city code is clear about trees in the right-of-way. No one may plant or remove a tree there except as the code allows. The owner of the adjoining property is responsible for maintaining it. And a permit to remove one obligates the owner to replace it with a species the city approves.</p>",
     "<p>Three details catch people out:</p>",
     "<ul><li><strong>Heavy pruning counts as removal.</strong> The code defines removal as cutting or removing 20 percent or more of the crown, trunk or root system. Hacking a street tree back by a third is, legally, removing it without a permit.</li><li><strong>Topping is prohibited</strong> on right-of-way trees, with narrow exceptions for utility work and storm damage.</li><li><strong>The right-of-way is wider than it looks.</strong> On streets with no planting strip it often extends several feet behind the sidewalk or the curb. A tree you think of as a front yard tree may be a street tree.</li></ul>",
     "<p>There is an emergency provision. If a right-of-way tree has to come down at once to avoid imminent injury or damage, the code treats that as a defense to removing it without a permit. Photograph the tree first, and tell the city afterward. See our <a href=\"/guides/beaverton-street-trees/\">street trees guide</a> for pruning, clearances and replacement.</p>")},
  {"h2": "Backyard trees: the protected kinds",
   "html": P("<p>Beaverton's development code protects specific categories of tree, not every tree over a certain size. If your tree is not in one of these groups, removing it generally needs no permit.</p>",
     "<ul><li><strong>Significant individual trees and historic trees.</strong> Specific trees the city has designated. There are not many, and owners are normally aware of them.</li><li><strong>Trees in significant groves.</strong> Mapped stands of native trees, often running through the back yards of several lots.</li><li><strong>Trees in significant natural resource areas.</strong> Creek corridors, wetlands and their buffers.</li><li><strong>Landscape trees.</strong> Trees required by an approved landscape plan, mainly on commercial, multifamily and common-area land.</li><li><strong>Mitigation trees.</strong> Trees planted to replace others that were removed under an earlier approval.</li><li><strong>Community trees.</strong> Healthy trees 10 inches across or more, measured four and a half feet up, that are not fruit or nut trees and not in any group above. A limited number may be removed in a calendar year without an application, and beyond that the code requires a Tree Plan. Published summaries of that limit disagree with each other, so ask the Planning Division for the figure that applies to your lot before removing several large trees in one year.</li></ul>",
     "<p>Pruning is regulated too. On protected trees, removing more than 10 percent of the canopy is major pruning, which needs approval.</p>")},
  {"h2": "How to find out what your tree is",
   "html": P("<ol><li><strong>Confirm you are inside the city.</strong> Look at your property tax statement. If the City of Beaverton isn't listed among the taxing districts, you are in unincorporated Washington County.</li><li><strong>Measure the tree.</strong> Wrap a tape around the trunk four and a half feet above the ground and divide by 3.14. Ten inches across is the community tree threshold.</li><li><strong>Look behind the fence.</strong> A creek, a wetland, a greenway or a band of native trees shared with your neighbors all suggest a buffer or a preserved grove.</li><li><strong>Read your covenants.</strong> Subdivisions built since about 1990 often list protected trees in the plat or the covenants, and the association may own the trees behind your lot.</li><li><strong>Call Planning with your address.</strong> The Planning Division at 503-526-2420 can tell you whether your lot has a mapped grove, a natural resource area or a tree-related condition of approval.</li></ol>",
     "<p>When we look at a removal, we do these checks before the job is scheduled, and the written estimate says what we found.</p>")},
  {"h2": "Outside Beaverton, the rules change", "small": "The post office decides your mailing address. It doesn't decide your tree rules.",
   "html": tabs("bv", [
      ("bv", "Beaverton", "City of Beaverton", "<p>Street trees need a permit to remove and are normally replaced. Backyard trees are regulated only in the protected categories above. Street trees must clear 8 feet over sidewalks, 12 feet over streets and 14 feet over arterials.</p>"),
      ("co", "Unincorporated county", "Aloha, Cedar Mill, Cedar Hills, Bethany, Oak Hills, Raleigh Hills, Garden Home", "<p>No city code applies. The county generally leaves trees on a developed home lot to the owner. The exceptions are mapped Significant Natural Resource areas and the vegetated corridors along creeks that Clean Water Services regulates. Roadside work that affects traffic needs a county right-of-way permit. Homeowners associations often add rules of their own.</p>"),
      ("hb", "Hillsboro", "City of Hillsboro", "<p>Hillsboro's code centers on the right-of-way. A free Tree Care Permit is required before planting, removing or replacing a street tree, and before major pruning: branches or roots 2 inches across or more, or over 20 percent of the crown. Clearance is 8 feet over sidewalks and 15 feet over streets.</p>"),
      ("tg", "Tigard", "City of Tigard", "<p>Tigard names six kinds of tree that need a removal permit: street trees, median trees, heritage trees, trees planted with the Urban Forestry Fund, trees required by a development approval, and native trees on sensitive lands such as steep slopes, floodplains, stream corridors and wetlands. Other trees on a single-family lot need none.</p>"),
      ("pd", "Portland edge", "City of Portland", "<p>If your street is on the Portland side of the county line, the rules are much stricter. Portland generally requires a permit to remove a private tree a foot or more across, and for all street trees. Raleigh Hills, Garden Home and West Slope residents near the line should confirm which side they are on.</p>")])
     + P("<p>Each of our <a href=\"/service-areas/\">service area pages</a> says which of these applies there.</p>")},
  {"h2": "Dead, dying and dangerous trees",
   "html": P("<p>A dead or failing tree is handled differently from a healthy one, but it isn't automatically exempt. For a street tree, the city still wants a permit unless the danger is immediate. For a protected tree, the usual route is a short written assessment of the tree's condition, photographs, and a call to Planning, which can often approve the removal quickly. Inside creek buffers, the city may ask that a safe length of trunk be left standing for wildlife.</p>",
     "<p>If a tree is an immediate threat to people or a building, deal with the danger first. Take dated photos before and after, keep the invoice, and notify the city once things are safe. That record is what shows the removal was necessary.</p>",
     "<h3 class=\"h3\">What happens if you cut without one</h3>",
     "<p>The city can require replacement trees, often several for each one removed, along with penalties. For trees that belonged to a neighbor or an association, Oregon's timber trespass law adds double or triple damages. Checking first takes one phone call, which is why we won't book a removal until the tree's status is settled.</p>")},
 ],
 "services": ["/tree-removal/", "/tree-trimming/", "/stump-removal/"],
 "related": ["beaverton-street-trees", "signs-tree-is-dangerous", "hire-tree-service-oregon"],
 "faq": [["Do I need a permit to cut down a tree on my own property in Beaverton?", "Usually not, if it is an ordinary yard tree. You do need approval for street trees, trees in significant groves or natural resource areas, landscape and mitigation trees, and designated significant or historic trees. Ask the Planning Division if unsure."],
         ["How do I know if my tree is a street tree?", "If it stands between the sidewalk and the curb, it is one. On streets without a planting strip, the right-of-way often extends several feet behind the sidewalk or the pavement, so a tree near the street may be one too. The city can confirm the line."],
         ["Can I remove a dead tree without a permit in Beaverton?", "Not automatically. A dead street tree still needs a permit unless it is an immediate danger, and dead trees inside creek buffers are usually protected as habitat. For an ordinary dead yard tree, no permit is needed."],
         ["Do Beaverton's tree rules apply in Aloha, Cedar Mill or Bethany?", "No. Those communities are unincorporated Washington County, even with a Beaverton or Portland mailing address. The county's rules apply there, which focus on natural resource areas, creek corridors and work in the road right-of-way."],
         ["Will you handle the permit?", "We check the tree's status before booking, tell you which approval applies, and supply the written assessment and photos the city or an association asks for. For street trees, the permit and the replacement are settled before the work is scheduled."]],
}

# ---------------------------------------------------------------- 2. emerald ash borer
EAB_SVG = ('<svg class="viz" viewBox="0 0 640 380" role="img" aria-labelledby="ea-t ea-d"><title id="ea-t">How to recognize an ash tree and the signs of emerald ash borer</title>'
 '<desc id="ea-d">Opposite branching compared with alternate branching, a compound ash leaf with seven leaflets, bark with D-shaped exit holes and S-shaped tunnels beneath, and a tree dying from the top down with sprouts on its trunk.</desc>'
 '<rect width="640" height="380" fill="#EEF2EC"/>'
 '<g data-layer="branch"><g fill="none" stroke="#6B4A2F" stroke-linecap="round"><path d="M200 350V40" stroke-width="9"/><path d="M200 290 120 240M200 290 280 240M200 200 130 150M200 200 270 150M200 110 150 70M200 110 250 70" stroke-width="6"/><path d="M470 350V40" stroke-width="9" stroke-opacity=".45"/><path d="M470 310 550 262M470 250 392 204M470 190 546 144M470 130 398 86" stroke-width="6" stroke-opacity=".45"/></g><g fill="#12382C"><circle cx="120" cy="240" r="5"/><circle cx="280" cy="240" r="5"/><circle cx="130" cy="150" r="5"/><circle cx="270" cy="150" r="5"/></g><text x="200" y="374" text-anchor="middle" class="t-strong keep">opposite: ash</text><text x="470" y="374" text-anchor="middle" class="keep">alternate: not ash</text></g>'
 '<g class="alt" data-layer="leaf"><path d="M150 330 490 96" fill="none" stroke="#2F6B4F" stroke-width="5" stroke-linecap="round"/><g fill="#5E9B74" stroke="#12382C" stroke-width="1.8"><ellipse cx="232" cy="228" rx="58" ry="20" transform="rotate(-80 232 228)"/><ellipse cx="292" cy="318" rx="58" ry="20" transform="rotate(10 292 318)"/><ellipse cx="318" cy="168" rx="58" ry="20" transform="rotate(-80 318 168)"/><ellipse cx="378" cy="258" rx="58" ry="20" transform="rotate(10 378 258)"/><ellipse cx="402" cy="110" rx="54" ry="19" transform="rotate(-80 402 110)"/><ellipse cx="460" cy="198" rx="54" ry="19" transform="rotate(10 460 198)"/><ellipse cx="538" cy="64" rx="56" ry="20" transform="rotate(-34 538 64)"/></g><text x="30" y="60" class="t-strong keep">5 to 9 leaflets, in pairs</text></g>'
 '<g class="alt" data-layer="holes"><rect x="170" y="30" width="300" height="320" fill="#8A6B4A" stroke="#12382C" stroke-width="2.5"/><path d="M210 30V350M262 30V350M318 30V350M372 30V350M428 30V350" stroke="#5E4630" stroke-width="5"/><rect x="292" y="150" width="150" height="150" fill="#E2CFA6" stroke="#12382C" stroke-width="2"/><path d="M306 176q36-22 60 0t60 0M306 222q36-22 60 0t60 0M306 268q36-22 60 0t60 0" fill="none" stroke="#6B4A2F" stroke-width="7" stroke-linecap="round"/><g fill="#1B1208"><path d="M206 84h10a7 7 0 0 1 0 14h-10Z"/><path d="M240 196h10a7 7 0 0 1 0 14h-10Z"/><path d="M220 292h10a7 7 0 0 1 0 14h-10Z"/><path d="M340 78h10a7 7 0 0 1 0 14h-10Z"/><path d="M410 112h10a7 7 0 0 1 0 14h-10Z"/></g><text x="486" y="100" class="t-strong keep">D-shaped</text><text x="486" y="126" class="t-strong keep">holes</text><text x="486" y="230" class="keep">tunnels</text><text x="486" y="256" class="keep">under bark</text></g>'
 '<g class="alt" data-layer="crown"><rect x="0" y="330" width="640" height="50" fill="#D9E5D3"/><path d="M308 330Q312 250 316 170L324 170Q328 250 334 330Z" fill="#CDAE84" stroke="#12382C" stroke-width="2.2"/><g fill="none" stroke="#6B4A2F" stroke-linecap="round" stroke-width="4"><path d="M320 170V40M320 120 270 70M320 120 372 66M320 84 296 44M320 84 346 40M320 150 250 120M320 150 392 116"/></g><g fill="#2F6B4F" fill-opacity=".6" stroke="#12382C" stroke-width="1.8"><ellipse cx="250" cy="200" rx="80" ry="46"/><ellipse cx="392" cy="196" rx="84" ry="48"/><ellipse cx="320" cy="232" rx="70" ry="36"/></g><g fill="#5E9B74" stroke="#12382C" stroke-width="1.4"><ellipse cx="300" cy="286" rx="14" ry="7"/><ellipse cx="342" cy="300" rx="14" ry="7"/><ellipse cx="302" cy="314" rx="12" ry="6"/></g><text x="430" y="70" class="t-strong keep">dies from the top</text><text x="356" y="310" class="keep">sprouts</text></g></svg>')

EAB = {
 "slug": "emerald-ash-borer-beaverton", "short": "Emerald ash borer in Beaverton", "form": "Tree removal",
 "title": "Emerald Ash Borer in Beaverton, OR | ID, Treat or Remove",
 "description": "Emerald ash borer is confirmed in Beaverton, OR. How to identify an ash, spot an attack, decide between treatment and removal, and follow the quarantine.",
 "og": "Confirmed in Beaverton in August 2026. How to tell if you have an ash, and what to do about it this year.",
 "h1": "Emerald ash borer in Beaverton: what to do about your ash trees",
 "card": "Confirmed in Beaverton and at Bethany Lake Park in August 2026. How to tell whether you have an ash, the signs of an attack, when treatment makes sense, and what the quarantine means for the wood.",
 "lede": "In August 2026 the Oregon Department of Forestry confirmed emerald ash borer in Beaverton and at Bethany Lake Park. It kills nearly every untreated ash it reaches, usually within a few years. The useful decisions are made before a tree shows symptoms, which for Beaverton means now.",
 "tldr": ["First find out <strong>whether you have an ash</strong>. Most people don't know. Look for opposite branching and leaves with five to nine leaflets.",
          "A healthy ash can be <strong>protected</strong> with trunk injections by a licensed applicator, repeated every two to three years.",
          "An ash that has lost more than about <strong>a third of its canopy</strong> is usually past saving.",
          "Dead ash turns <strong>brittle</strong> quickly. Removal gets riskier the longer you wait.",
          "Washington County is under <strong>quarantine</strong>. Ash wood, chips and any hardwood firewood must not leave the quarantine area."],
 "sections": [
  {"h2": "What has happened, and why it matters",
   "html": P("<p>Emerald ash borer is a small metallic-green beetle from Asia, first found in Michigan in 2002. Its larvae feed under the bark of ash trees and cut off the flow of water and sugars. It has since killed hundreds of millions of ash across North America. In the cities it reached early, almost no untreated ash survived.</p>",
     "<p>Oregon's first detection was in Forest Grove in 2022, the first on the West Coast. The state set a permanent quarantine that now covers Washington, Yamhill, Marion, Clackamas and Multnomah counties. The August 2026 finds in Beaverton and at Bethany Lake Park show the beetle moving east through the Tualatin Valley, as expected.</p>",
     "<p>It matters here because ash is common. Native Oregon ash lines Fanno Creek, Beaverton Creek, Rock Creek and nearly every wet swale in the valley, and ash cultivars were planted widely as street and yard trees from the 1980s on. The beetle also attacks olive trees and white fringetree. Mountain-ash, despite the name, is not a true ash and is not affected.</p>")},
  {"h2": "Is it an ash, and is it under attack?", "small": "Four things to look for. The first two tell you whether it is an ash, the second two whether the borer is in it.",
   "html": tabs("branch", [
      ("branch", "Branching", "Opposite branching", "<p>On an ash, twigs and buds grow in pairs, directly across from each other. Most trees have alternate branching, where they are staggered. Around here only ash, maples, dogwoods and a few others are opposite, and maples and dogwoods have simple leaves, which settles it.</p>"),
      ("leaf", "Leaf", "A compound leaf with 5 to 9 leaflets", "<p>Each ash leaf is made up of five to nine leaflets arranged in pairs along a central stalk, with a single leaflet at the tip. Walnut and tree-of-heaven have similar leaves but alternate branching. In winter, look for the clusters of paddle-shaped seeds that hang on female trees.</p>"),
      ("holes", "Bark", "D-shaped exit holes and S-shaped tunnels", "<p>Adult beetles chew their way out through holes about an eighth of an inch across and flat on one side, like a capital D. They are hard to spot and often start high in the tree. Where bark has split or been stripped by woodpeckers, you can see the winding, S-shaped tunnels the larvae made.</p>"),
      ("crown", "Crown", "Dying from the top down", "<p>The canopy thins from the top, because that is where attacks begin. Below the dying part, the tree pushes out clumps of new sprouts from the trunk and main limbs. Pale patches where woodpeckers have flaked off the outer bark, called blonding, are often the first sign you can see from the ground.</p>")],
      top=EAB_SVG, hint="<h2>Know your ash.</h2> Pick what you are looking at.")},
  {"h2": "Treat it or remove it?", "small": "It depends mostly on how much canopy the tree still has.",
   "html": chooser("eab-pick", "How does your ash look right now?", [
      ("full", "Full, healthy canopy", "Worth protecting, if the tree is worth keeping.", "<p>This is the best time to act. A healthy, well-placed ash can be protected with trunk injections before the borer reaches it. Decide tree by tree: a large shade tree in a good spot justifies treatment, while a small or badly placed one may be better replaced on your own schedule.</p>"),
      ("thin", "Some thinning at the top, under a third", "Still treatable. Decide this season.", "<p>Trees with less than about 30 percent canopy loss usually respond to treatment, because enough of the tree's plumbing still works to carry the insecticide. Have the tree assessed now. Next year it may be on the other side of the line.</p>"),
      ("half", "A third to half of the canopy gone", "Usually past saving. Plan the removal.", "<p>Once this much of the crown has died, treatment rarely brings the tree back, and what survives is a weakened tree with a lot of dead wood in it. Schedule removal while the wood is still sound enough to climb and rig safely.</p>"),
      ("dead", "Mostly or completely dead", "Remove it soon, and keep clear of it.", "<p>Dead ash dries out and becomes brittle far faster than most trees. Limbs snap without warning and the trunk can break during removal, so these jobs take extra care and sometimes a lift. Keep people, cars and play equipment out from under it until it is down.</p>"),
      ("small", "It is small, or in a poor spot", "Replace it on your own terms.", "<p>A young ash, or one under wires or crowding a building, is rarely worth years of treatment. Take it out at a convenient time, have the stump removed, and plant something that isn't an ash. Doing it before the tree is infested keeps the job simple.</p>")])
     + P("<p>We assess ash, tell you honestly which group each tree falls in, and remove the ones that have to go. Treatment itself is done by licensed pesticide applicators, and we can point you to one.</p>")},
  {"h2": "What treatment involves",
   "html": P("<p>The treatment with the best record is a trunk injection of emamectin benzoate. A licensed applicator drills small holes around the base of the trunk and injects the product, which the tree carries up into its canopy. One treatment protects for two to three years, and then it has to be repeated for as long as you want to keep the tree.</p>",
     "<ul><li><strong>Timing.</strong> Injections are done in the growing season, from mid-spring to early summer, when the tree is moving water.</li><li><strong>Who can do it.</strong> In Oregon, applying pesticides to someone else's trees requires a state license. Soil drenches sold to homeowners are much less reliable on large trees.</li><li><strong>What it can't do.</strong> It doesn't repair damage already done. A treated tree with a dead top still has a dead top, which needs pruning out.</li><li><strong>Near water.</strong> Along creeks and wetlands, product choice and method are restricted. Ask the applicator about buffers.</li></ul>",
     "<p>Treatment makes most sense for mature, healthy ash that shade a house, anchor a garden or line a street, where replacing the tree's benefits would take decades.</p>")},
  {"h2": "Removal and the quarantine",
   "html": P("<p>The state quarantine covers all of Washington County. Inside it, ash, olive and white fringetree material, and hardwood firewood of any species, can't be moved out of the quarantine area. For a homeowner that means three things.</p>",
     "<ul><li>Wood and chips from a removed ash stay on your property or go to a disposal site inside the quarantine area. We handle that as part of the job.</li><li>Don't take firewood from home to a campsite, and don't bring any back. Moving firewood is how the beetle jumps tens of miles at a time.</li><li>Buy firewood where you burn it.</li></ul>",
     "<p>Timing matters for removal as well. An ash that is removed green behaves like any other tree. An ash that has been dead for two or three years is brittle, unpredictable and more dangerous for the crew, which makes the work slower. The park district has already begun taking out ash along some of its trails for that reason.</p>",
     "<h3 class=\"h3\">What to plant instead</h3>",
     "<p>The lesson of ash is not to plant too much of any one thing. Pick a replacement suited to the space and different from what your neighbors have. For wet ground where Oregon ash grew, red alder, Pacific willow, black hawthorn and Oregon white oak on the drier edge are native choices. For street trees inside the city, the replacement has to come from Beaverton's approved list.</p>")},
 ],
 "services": ["/tree-removal/", "/tree-trimming/", "/stump-removal/"],
 "related": ["beaverton-tree-problems", "signs-tree-is-dangerous", "beaverton-street-trees"],
 "faq": [["Is emerald ash borer in Beaverton?", "Yes. The Oregon Department of Forestry confirmed it in Beaverton and at Bethany Lake Park in August 2026. It was first found in Oregon in Forest Grove in 2022. All of Washington County is inside the state's permanent quarantine."],
         ["How do I know if my tree is an ash?", "Look for opposite branching, where twigs grow in pairs across from each other, and compound leaves with five to nine leaflets. Female trees carry clusters of paddle-shaped seeds. Mountain-ash is not a true ash and isn't affected."],
         ["Can an ash tree be saved from emerald ash borer?", "Yes, if treatment starts while the tree is healthy or has lost less than about 30 percent of its canopy. Trunk injections by a licensed applicator protect it for two to three years at a time and have to be repeated."],
         ["Should I remove my ash before it gets infested?", "Only if it isn't worth treating: a small tree, a poorly placed one, or one already in decline. A large healthy ash in a good spot is usually worth protecting. Whatever you decide, deciding early keeps your options open."],
         ["Can I keep or give away the firewood from my ash?", "You can keep and burn it on your own property. It must not leave the quarantine area, and neither may any other hardwood firewood. Don't take it camping and don't give it to someone outside the quarantine counties."]],
}

# ---------------------------------------------------------------- 3. street trees
STREET_SVG = ('<svg class="viz" viewBox="0 0 640 380" role="img" aria-labelledby="st-t st-d"><title id="st-t">Cross-section of a Beaverton street showing the right-of-way and required branch clearances</title>'
 '<desc id="st-d">A street tree in the planting strip between the street and the sidewalk. Branches must clear 8 feet over the sidewalk and 12 feet over the street, or 14 feet over an arterial. The right-of-way runs from the street to the property line behind the sidewalk.</desc>'
 '<rect width="640" height="380" fill="#EEF2EC"/><rect x="0" y="280" width="250" height="22" fill="#9AA39D"/><rect x="250" y="272" width="12" height="30" fill="#C9D0CA" stroke="#7E8F86" stroke-width="1.5"/><rect x="262" y="276" width="78" height="26" fill="#A9C8A0"/><rect x="340" y="274" width="84" height="10" fill="#E3E6E0" stroke="#B9C3BA" stroke-width="1.5"/><rect x="340" y="284" width="84" height="18" fill="#CDBD9F"/><rect x="424" y="276" width="216" height="26" fill="#A9C8A0"/><rect x="0" y="302" width="640" height="78" fill="#CDBD9F"/>'
 '<g stroke="#12382C" stroke-width="2.2"><rect x="520" y="196" width="120" height="80" fill="#fff"/><path d="M506 196 590 140 674 196Z" fill="#fff"/></g>'
 '<ellipse cx="300" cy="112" rx="172" ry="76" fill="#2F6B4F" fill-opacity=".5" stroke="#12382C" stroke-width="2"/><path d="M293 276Q296 220 297 180L305 180Q306 220 309 276Z" fill="#CDAE84" stroke="#12382C" stroke-width="2.2"/>'
 '<g stroke="#12382C" stroke-width="2" fill="#B9C7D6"><rect x="58" y="196" width="120" height="70" rx="5"/><rect x="178" y="220" width="34" height="46" rx="4"/></g><circle cx="92" cy="272" r="12" fill="#12382C"/><circle cx="186" cy="272" r="12" fill="#12382C"/>'
 '<g stroke="#C73E1D" stroke-width="2.5" fill="none"><path d="M140 280V181M132 191l8-10 8 10M132 270l8 10 8-10"/><path d="M382 274V208M374 218l8-10 8 10M374 264l8 10 8-10"/></g>'
 '<path d="M424 150V340" stroke="#12382C" stroke-width="2" stroke-dasharray="8 6"/>'
 '<text x="150" y="176" class="t-strong keep">12 ft</text><text x="392" y="204" class="t-strong keep">8 ft</text><text x="16" y="330" class="t-strong keep">right-of-way</text><text x="440" y="330" class="t-strong keep">your lot</text>'
 '<text x="16" y="352">street, strip and sidewalk: city permit to remove a tree</text><text x="432" y="146">property line</text><text x="16" y="164">14 ft on arterials</text></svg>')

STREET = {
 "slug": "beaverton-street-trees", "short": "Beaverton street trees", "form": "Tree trimming and maintenance",
 "title": "Beaverton Street Trees | Who Prunes, Removes and Replaces",
 "description": "Beaverton street trees explained: who maintains them, clearance heights, the 20 percent rule, removal permits, replacements and sidewalk damage.",
 "og": "You maintain it, the city permits it. Clearances, pruning limits, removal, replacement and sidewalks.",
 "h1": "Beaverton street trees: who prunes, who removes, who replaces",
 "card": "You maintain the tree in front of your house, and the city decides whether it can come out. Clearance heights, the 20 percent pruning rule, replacements, sidewalks and leaves.",
 "lede": "The tree between your sidewalk and the street is an odd piece of property. It stands on public land, the city controls whether it lives or dies, and yet the job of looking after it is yours. This guide covers what that means in practice.",
 "tldr": ["The <strong>adjoining owner maintains</strong> a street tree: pruning, watering, clearance.",
          "Branches must clear <strong>8 feet</strong> over the sidewalk, <strong>12 feet</strong> over the street and <strong>14 feet</strong> over an arterial.",
          "<strong>Removing</strong> one needs a city permit, and a replacement from the approved list is normally required.",
          "Cutting <strong>20 percent or more</strong> of the crown or roots counts as removal. Topping is prohibited.",
          "In <strong>unincorporated</strong> areas, Hillsboro and Tigard the rules differ. See the last section."],
 "sections": [
  {"h2": "What counts as a street tree",
   "html": P("<p>A street tree is any tree in the public right-of-way, which is the strip of public land that holds the street, the curb, the planting strip and the sidewalk. The property line is usually a foot or so behind the sidewalk, not at the curb.</p>",
     "<p>On streets without a planting strip, the right-of-way still exists, and it often reaches several feet into what looks like your front lawn. A tree planted near the street on one of those lots may legally be a street tree. If you are unsure, the city can tell you where the line runs for your address.</p>")
     + figure(STREET_SVG, "The right-of-way runs from the street to the property line behind the sidewalk. Red arrows show the clearances the city code requires.")},
  {"h2": "Who does what", "small": "Six situations, and whose job each one is.",
   "html": tabs("prune", [
      ("prune", "Pruning", "Pruning is the adjoining owner's job", "<p>City code makes the owner or occupant of the adjoining property responsible for maintaining right-of-way trees, and it requires the work to follow recognized arboriculture standards or be supervised by an ISA certified arborist. Keep each pruning under 20 percent of the crown. The city prunes only along certain arterials where a wall or fence separates the houses from the street.</p>"),
      ("remove", "Removal", "Removal needs a city permit", "<p>Nobody may remove a right-of-way tree without one. The city wants a reason, such as death, disease, structural failure or serious damage to paving or pipes. Leaves, shade and general inconvenience are not usually accepted. Apply before you schedule the work. We supply photos and a written assessment when they help.</p>"),
      ("plant", "Replacement", "A replacement is normally required", "<p>A removal permit obligates the owner to plant a new tree of a species the city approves, in a suitable spot. The old stump has to come out first, since a new tree won't establish in rotting wood. Under wires and in narrow strips, pick a small-maturing species.</p>"),
      ("walk", "Sidewalk damage", "Roots and sidewalks", "<p>In Beaverton, as in most Oregon cities, keeping the sidewalk in repair generally falls to the adjoining owner. Don't solve a lifted panel by cutting big roots yourself. Removing large roots on one side can destabilize the tree, and cutting 20 percent or more of the root system counts as removing it. Ask us and the city before the concrete crew arrives.</p>"),
      ("leaf", "Leaves and fruit", "Leaves are yours too", "<p>Raking and disposing of a street tree's leaves is the adjoining owner's task, and the city runs leaf drop-off events each fall to help. Keep storm drains clear in front of your house, because a blocked drain floods the street and your own driveway first.</p>"),
      ("storm", "Storm damage", "After a storm", "<p>A broken limb hanging over the street or sidewalk is urgent, and dealing with it is still the adjoining owner's responsibility. If the tree has to come down at once to prevent injury or damage, the code recognizes emergency removal. Photograph it first and tell the city afterward. If wires are involved, call PGE before anyone else.</p>")])},
  {"h2": "The clearance numbers, and why they exist",
   "html": P("<p>Beaverton's code requires that no part of a right-of-way tree hang lower than <strong>8 feet above a sidewalk</strong> or path, <strong>12 feet above a street</strong>, or <strong>14 feet above an arterial</strong>. A separate section asks owners to keep trees and shrubs on their own lots at least 8 feet above sidewalks and 10 feet above the roadway where they overhang.</p>",
     "<p>The numbers come from what uses the space. Eight feet clears a tall pedestrian with an umbrella and a cyclist standing on the pedals. Twelve to fourteen feet clears garbage trucks, school buses, delivery vans and fire engines, all of which break low limbs, and get damaged by them, when the clearance isn't there.</p>",
     "<p>Raising a crown properly means removing whole lower limbs back to the trunk or to a large side branch, a few at a time over several years. It does not mean shearing the underside flat. On a young tree, start early: taking off a one-inch limb at year five is kinder than taking off a six-inch limb at year twenty.</p>")},
  {"h2": "What you may not do",
   "html": P("<ul><li><strong>Top it.</strong> The code prohibits topping right-of-way trees. Topping also ruins the tree, producing weak sprouts over decaying cuts.</li><li><strong>Prune away a fifth or more at once.</strong> Removing 20 percent or more of the crown, trunk or root system is treated as removal, which needs a permit.</li><li><strong>Remove it because you dislike it.</strong> Permits are granted for the condition of the tree or the damage it causes, not for taste.</li><li><strong>Plant whatever you like.</strong> New and replacement street trees come from the city's approved list, matched to the width of the strip and whatever is overhead.</li><li><strong>Work near the power lines.</strong> Trees growing into the high-voltage lines are pruned by PGE's line-clearance crews. Stay 20 feet from lines yourself.</li></ul>")},
  {"h2": "Choosing a replacement",
   "html": P("<p>Most street tree problems are planting problems thirty years on: a large-maturing tree in a four-foot strip, or a tall one under the wires. Picking the right size of tree for the space is the single decision that matters most.</p>",
     "<ul><li><strong>Narrow strips, under 4 feet, or under power lines:</strong> small-maturing trees that top out around 25 feet.</li><li><strong>Strips of 4 to 6 feet:</strong> medium trees, 30 to 45 feet.</li><li><strong>Wide strips with nothing overhead:</strong> large shade trees, which give the most benefit and live the longest.</li></ul>",
     "<p>Avoid ash, now that emerald ash borer is in Beaverton, and avoid ornamental pear and sweetgum, which split in ice. Try to plant something different from the trees either side of you, so that the next pest or storm doesn't take the whole street at once. Plant in fall if you can, and water through the first three summers.</p>")},
  {"h2": "Outside Beaverton city limits",
   "html": P("<ul><li><strong>Unincorporated Washington County</strong> (Aloha, Cedar Mill, Cedar Hills, Bethany and others): roadside trees are generally the adjoining owner's responsibility. There is no street tree removal permit, but work that affects traffic on a county road needs a right-of-way permit. Homeowners associations often set their own rules.</li><li><strong>Hillsboro:</strong> a free Tree Care Permit is needed to plant, remove or replace a street tree and for major pruning. Clearance is 8 feet over sidewalks and 15 feet over streets.</li><li><strong>Tigard:</strong> street trees need a removal permit, replacements are usually required, and clearance is 8 feet over sidewalks and 13 to 18 feet over streets depending on the street type.</li></ul>",
     "<p>The <a href=\"/guides/beaverton-tree-removal-permit/\">permit guide</a> covers private trees, and each <a href=\"/service-areas/\">service area page</a> says which rules apply there.</p>")},
 ],
 "services": ["/tree-trimming/", "/tree-removal/", "/stump-removal/"],
 "related": ["beaverton-tree-removal-permit", "best-time-to-prune-oregon", "emerald-ash-borer-beaverton"],
 "faq": [["Who is responsible for street trees in Beaverton?", "The owner of the adjoining property maintains them, including pruning and clearance. The city controls removal through a permit and normally requires a replacement. The city itself maintains trees only along some arterials separated from homes by a wall or fence."],
         ["How high do branches have to be over the sidewalk in Beaverton?", "Eight feet over sidewalks and paths, 12 feet over streets, and 14 feet over arterials. For trees on your own lot that overhang the right-of-way, the code asks for 8 feet over sidewalks and 10 feet over the roadway."],
         ["Can I remove the street tree in front of my house?", "Only with a city permit. The city looks at the tree's condition and the damage it causes, and normally requires a replacement from its approved list. Removing one without a permit can bring penalties and a replanting order."],
         ["Can I cut the roots that are lifting my sidewalk?", "Be careful. Large roots hold the tree up, and cutting 20 percent or more of the root system legally counts as removing the tree. Have the tree looked at first. Options include ramping or re-routing the walk, or a permitted removal and replacement."],
         ["Does the city prune street trees for me?", "Generally not. Maintenance is the adjoining owner's job. PGE prunes trees that grow into its high-voltage lines, for clearance and not for the tree's shape, which is one reason to plant small trees under wires."]],
}

GUIDES = [PERMIT, EAB, STREET]
